server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/open_judge?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=PRC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  # Specify the DBMS
  jpa:
    database : MYSQL
  # Show or not log for each sql query
    show-sql : true
  # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto : update
  # Naming strategy
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  # stripped before adding them to the entity manager)
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type : text/html
  freemarker:
    charset: UTF-8

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms